[package]
name = "methods"
version = "0.1.0"
edition = "2021"

[build-dependencies]
risc0-build = {git = "https://github.com/risc0/risc0.git", rev = "0622ee999402b8ae805e59ac3b19d0a2e2eb55ae"}

[package.metadata.risc0]
methods = ["guest"]
